language: ruby
cache: bundler
dist: trusty
rvm:
  - rbx-3
  - 2.5
  - truffleruby

before_install:
  - apt install -y graphviz

script:
  - ls
  - rake install
  - camtool -v

notifications:
  slack: camflow:T3Umf9cAIwKnaxFEkjeZV7RM
