language: ruby
cache: bundler
dist: trusty
rvm:
  - 2.5
  - 2.6
  - truffleruby

before_install:
  - sudo apt-get install -y graphviz

script:
  - ls
  - rake install
  - camtool -v

notifications:
  slack: camflow:T3Umf9cAIwKnaxFEkjeZV7RM

deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  gem: camtool
  on:
    tags: true
